import { useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Check, Download, FileCheck2, FileText, ShieldCheck, CircleAlert, Plus, Wallet, ArrowUpRight } from 'lucide-react';
import { api, post, aed, downloadQuote, type Config } from './api';
import { ProfileEditor } from './ProfileEditor';
import { Conversation } from './Conversation';
import { ReadAloud } from './Voice';
import { Providers } from './Providers';

export function Loading() { return <div className="loading" role="status">Loading your workspace…</div>; }
export function ErrorView({ error }: { error: unknown }) { return <div className="error" role="alert">{error instanceof Error ? error.message : 'This page could not load. Please try again.'}</div>; }

export function Dashboard() {
  const navigate = useNavigate(); const query = useQueryClient(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [showImport, setShowImport] = useState(false);
  const policies = useQuery({ queryKey: ['policies'], queryFn: () => api('/api/policies') });
  const cases = useQuery({ queryKey: ['cases'], queryFn: () => api('/api/cases') });
  async function start() { setBusy(true); setError(''); try { const result = await post('/api/cases'); navigate(`/app/intake/${result.id}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function importPolicy(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    try { const result = await post('/api/policies/import', Object.fromEntries(form)); await query.invalidateQueries({ queryKey: ['policies'] }); navigate(`/app/policies/${result.id}`); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <><div className="page-heading"><div><span className="eyebrow">YOUR COVER, CONNECTED</span><h1>A little clarity.<br/>A lot more confidence.</h1><p>Find the right fit today. Keep the important details together tomorrow.</p></div><button onClick={start} disabled={busy}><Plus size={18}/> Find my cover</button></div>
    <div className="journey-banner"><div className="banner-icon"><ShieldCheck size={30}/></div><div><h2>Your health cover, one clear step at a time.</h2><p>Tell us about yourself. Compare the tradeoffs. Choose with understanding.</p></div><span className="badge light">Synthetic demonstration</span></div>
    <div className="section-heading"><h2>Your policies</h2><button className="quiet" onClick={() => setShowImport(!showImport)}><Plus size={16}/> Add existing policy</button></div>
    {showImport && <form className="import-form surface" onSubmit={importPolicy}><p>Imported details remain unverified until policy evidence is reviewed. No benefit or payment balances will be inferred.</p><div className="form-grid"><label className="field">Plan name<input name="plan_name" required maxLength={100}/></label><label className="field">Insurer name<input name="insurer_name" required maxLength={100}/></label><label className="field">Start date<input name="start_date" type="date" required/></label></div><button disabled={busy}>Save unverified policy</button></form>}
    {policies.isLoading ? <Loading/> : policies.error ? <ErrorView error={policies.error}/> : policies.data?.length ? <div className="policy-grid">{policies.data.map((policy: any) => <Link className="policy-card" to={`/app/policies/${policy.id}`} key={policy.id}><span className="plan-mark"><ShieldCheck size={23}/></span><span className="badge neutral">{policy.status === 'demo_active' ? 'Demo policy' : 'Unverified import'}</span><h3>{policy.plan.name}</h3><p>Coverage start · {policy.start_date}</p><div className="card-bottom"><span>{policy.plan.annual_premium ? `${aed(policy.plan.annual_premium * 100)} / year` : 'Terms need verification'}</span><ArrowUpRight size={20}/></div></Link>)}</div> : <div className="empty-state"><ShieldCheck size={32}/><h3>A clearer picture starts here.</h3><p>Your saved policies will appear here once you complete the guided journey.</p><button className="secondary" onClick={start} disabled={busy}>Start my profile <ArrowRight size={17}/></button></div>}
    {!!cases.data?.length && <section className="recent"><h2>Pick up where you left off</h2>{cases.data.map((item: any, index: number) => <Link className="list-row" key={item.id} to={`/app/intake/${item.id}`}><span className="list-icon"><FileText size={21}/></span><div><strong>Insurance profile {cases.data.length - index}</strong><small>Started {new Date(item.created_at).toLocaleDateString('en-GB')} · Details saved</small></div><ArrowRight size={18}/></Link>)}</section>}
    {error && <ErrorView error={new Error(error)}/>}</>;
}

export function Intake({ config }: { config: Config }) {
  const { caseId = '' } = useParams(); const query = useQueryClient(); const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const profile = useQuery({ queryKey: ['profile'], queryFn: () => api('/api/me/profile') });
  async function quote() { setBusy(true); setError(''); try { const result = await post(`/api/cases/${caseId}/quotes`); navigate(`/app/quotes/${result.id}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (profile.isLoading) return <Loading/>; if (profile.error) return <ErrorView error={profile.error}/>;
  return <><div className="page-heading compact"><div><span className="eyebrow">01 / UNDERSTAND YOUR NEEDS</span><h1>Good cover starts with you.</h1><p>Speak naturally, type, or edit your details. We’ll keep everything in one place.</p></div><button disabled={busy || !profile.data.readiness.ready} onClick={quote}>Get quotation <ArrowRight size={17}/></button></div>
    {!config.ai_available && <div className="notice"><CircleAlert size={18}/><span>AI and voice need a configured Groq key. The profile editor is available; no generated answers are being simulated.</span></div>}
    {error && <ErrorView error={new Error(error)}/>}<div className="intake-layout"><Conversation caseId={caseId} profile={profile.data} voice={config.voice_available}/><ProfileEditor profile={profile.data} onSaved={() => { void query.invalidateQueries({ queryKey: ['profile'] }); }}/></div></>;
}

export function QuotePage() {
  const { quoteId = '' } = useParams(); const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const quote = useQuery({ queryKey: ['quote', quoteId], queryFn: () => api(`/api/quotes/${quoteId}`) });
  const sources = useQuery({ queryKey: ['public-sources'], queryFn: () => api('/api/sources') });
  async function prepare(id: string) { setBusy(true); setError(''); try { const result = await post('/api/applications/prepare', { quote_id: quoteId, plan_id: id }); navigate(`/app/applications/${result.id}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (quote.isLoading) return <Loading/>; if (quote.error) return <ErrorView error={quote.error}/>; const data = quote.data;
  return <><div className="page-heading compact"><div><span className="eyebrow">02 / SEE YOUR OPTIONS</span><h1>Compare the things that matter.</h1><p>Three fictional plans. Clear prices. Tradeoffs worth understanding.</p></div><Link className="text-link" to={`/app/intake/${data.case_id || ''}`}>Back to profile</Link></div>
    <div className="quote-banner"><FileText size={31}/><div><h2>Your indicative quotation</h2><p>{data.applicant_name} · Prepared {new Date(data.generated_at).toLocaleDateString('en-GB')} · Not an insurer-issued offer</p></div><button className="secondary" onClick={() => downloadQuote(quoteId).catch(e => setError(e.message))}><Download size={17}/> Download PDF</button></div>
    {data.stale && <div className="notice">Your profile or catalogue changed. Return to your profile and generate a fresh quote before selecting a plan.</div>}
    {!data.recommended_plan_id && <div className="notice">No plan meets all known requirements yet. Review the gaps below and clarify your needs; no unsuitable plan is selected automatically.</div>}
    {error && <ErrorView error={new Error(error)}/>}<div className="plan-grid">{data.items.map((item: any) => { const p = item.plan; const recommended = p.id === data.recommended_plan_id; return <article className={`plan-card ${recommended ? 'recommended' : ''}`} key={p.id}>
      <div className="plan-top"><span className="eyebrow">{p.network.toUpperCase()} NETWORK</span>{recommended && <span className="badge">Best fit here</span>}</div><h2>{p.name}</h2><div className="plan-price">{aed(item.premium_fils)}<small>/ year</small></div><p className="muted">{aed(item.monthly_budget_equivalent_fils)} monthly budget equivalent</p><hr/>
      <dl className="term-list"><div><dt>Annual cover limit</dt><dd>{aed(p.annual_limit * 100)}</dd></div><div><dt>Deductible</dt><dd>{aed(p.deductible * 100)}</dd></div><div><dt>Member copay</dt><dd>{p.outpatient_copay_pct}%</dd></div><div><dt>Maternity wait</dt><dd>{p.maternity.covered ? `${p.maternity.waiting_period_months} months` : 'Excluded'}</dd></div><div><dt>Existing-condition wait</dt><dd>{p.chronic_preexisting.covered ? `${p.chronic_preexisting.waiting_period_months} months` : 'Excluded'}</dd></div></dl>
      <div className="plan-reasons"><strong>{recommended ? 'Why this fits' : 'The tradeoff'}</strong>{item.reasons.map((reason: string) => <p key={reason}><Check size={15}/>{reason}</p>)}{[...item.gaps, ...item.unknowns].map((reason: string) => <p className="gap" key={reason}><CircleAlert size={15}/>{reason}</p>)}</div>
      <ReadAloud text={`${p.name}. Annual premium ${p.annual_premium} dirhams. ${[...item.reasons, ...item.gaps, ...item.unknowns].join(' ')}`}/><button disabled={busy || data.stale || item.status !== 'supported'} onClick={() => prepare(p.id)}>Easy Fill <ArrowRight size={17}/></button><small className="source-label">Source: fictional catalogue v3 · {p.id}</small></article>; })}</div>
    <section className="surface comparison"><h2>Your needs, side by side</h2><div className="table-scroll" tabIndex={0} aria-label="Plan comparison, scroll horizontally"><table><thead><tr><th>Benefit</th>{data.items.map((x: any) => <th key={x.plan.id}>{x.plan.name}</th>)}</tr></thead><tbody>{['network', 'dental_optical'].map(key => <tr key={key}><th>{key.replaceAll('_', ' ')}</th>{data.items.map((x: any) => <td key={x.plan.id}>{x.plan[key]}</td>)}</tr>)}<tr><th>Maternity limit</th>{data.items.map((x: any) => <td key={x.plan.id}>{x.plan.maternity.covered ? aed(x.plan.maternity.limit * 100) : 'Excluded'}</td>)}</tr><tr><th>Meets your requirements</th>{data.items.map((x: any) => <td key={x.plan.id}>{x.status.replaceAll('_', ' ')}</td>)}</tr></tbody></table></div><p className="muted">The recommendation is among these three plans only. Monthly equivalents are budgeting information, not an instalment offer.</p></section>
    <section className="surface"><h2>Explore official information</h2><p className="muted">These public insurer pages are for independent research. They do not supply prices or terms for the fictional plans above.</p>{sources.data?.items.map((source: any) => <p key={source.id}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.insurer} · {source.title}</a><small className="source-label">{source.last_checked ? ` Source checked ${new Date(source.last_checked).toLocaleDateString('en-GB')}; facts still unreviewed.` : ' Source has not been checked locally.'}</small></p>)}{sources.error && <p className="muted">Official research links are temporarily unavailable.</p>}</section></>;
}

function flatten(value: any, prefix = ''): [string, string][] { return Object.entries(value).flatMap(([key, item]) => item && typeof item === 'object' && !Array.isArray(item) ? flatten(item, prefix ? `${prefix} · ${key}` : key) : [[(prefix ? `${prefix} · ` : '') + key, Array.isArray(item) ? item.join(', ') : item == null ? 'Not provided' : String(item)]]); }
export function ApplicationPage() {
  const { applicationId = '' } = useParams(); const navigate = useNavigate(); const query = useQueryClient(); const [checked, setChecked] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const application = useQuery({ queryKey: ['application', applicationId], queryFn: () => api(`/api/applications/${applicationId}`) });
  async function submit() { setBusy(true); setError(''); try { const result = await post(`/api/applications/${applicationId}/submit`, { payload_hash: application.data.payload_hash, declarations_confirmed: checked }); await query.invalidateQueries({ queryKey: ['policies'] }); navigate(`/app/policies/${result.policy_id}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (application.isLoading) return <Loading/>; if (application.error) return <ErrorView error={application.error}/>; const data = application.data;
  return <><div className="page-heading compact"><div><span className="eyebrow">03 / REVIEW YOUR CHOICE</span><h1>The details are ready.<br/>The decision is yours.</h1><p>Easy Fill has used your saved profile. Check the application before you submit.</p></div><FileCheck2 className="heading-icon" size={54}/></div>
    <div className="application-layout"><section className="surface"><div className="section-heading"><h2>Your application</h2><span className="badge neutral">Prepared from saved details</span></div><dl className="application-fields">{flatten(data.payload).map(([key, value]) => <div key={key}><dt>{key.replaceAll('_', ' ').replace(/([a-z])([A-Z])/g, '$1 $2')}</dt><dd>{value}</dd></div>)}</dl></section><aside className="selection-summary"><span className="eyebrow">YOUR SELECTED PLAN</span><h2>{data.plan.name}</h2><p className="plan-price">{aed(data.plan.annual_premium * 100)}<small>/ year</small></p><dl className="term-list"><div><dt>Cover starts</dt><dd>{data.start_date}</dd></div><div><dt>Network</dt><dd>{data.plan.network}</dd></div><div><dt>Destination</dt><dd>Helm in-app sandbox</dd></div></dl><p className="muted">This creates a demonstration policy. It does not submit to a real insurer or issue real cover. Monthly schedules, if selected, are simulated.</p><label className="checkbox"><input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)}/><span>I have reviewed these details and authorize this exact sandbox application.</span></label><button disabled={!checked || busy || data.status !== 'ready_for_confirmation'} onClick={submit}>Confirm and submit <ArrowRight size={17}/></button><Link to={`/app/quotes/${data.quote_id || ''}`} className="text-link">Back to comparison</Link></aside></div>{error && <ErrorView error={new Error(error)}/>}</>;
}

declare global { interface Window { Razorpay?: new (options: any) => { open(): void; on(event: string, fn: (data: any) => void): void }; } }
async function loadCheckout() {
  if (window.Razorpay) return;
  await new Promise<void>((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.onload = () => resolve(); script.onerror = () => reject(new Error('Could not load test checkout.')); document.head.appendChild(script); });
}

export function PolicyPage({ config }: { config: Config }) {
  const { policyId = '' } = useParams(); const query = useQueryClient(); const [order, setOrder] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [tab, setTab] = useState('Overview');
  const policy = useQuery({ queryKey: ['policy', policyId], queryFn: () => api(`/api/policies/${policyId}`) });
  const profile = useQuery({ queryKey: ['profile'], queryFn: () => api('/api/me/profile') });
  const cases = useQuery({ queryKey: ['cases'], queryFn: () => api('/api/cases') });
  const notices = useQuery({ queryKey: ['updates', policyId], queryFn: () => api(`/api/policies/${policyId}/updates`) });
  async function pay(id: string) {
    setBusy(true); setError('');
    try {
      const result = await post(`/api/instalments/${id}/payment-order`);
      if (result.provider === 'simulator') setOrder(result);
      else {
        await loadCheckout(); const Checkout = window.Razorpay!;
        const checkout = new Checkout({ key: result.key_id, order_id: result.provider_order_id, amount: result.amount, currency: result.currency, name: 'Helm AI · Test payment',
          handler: async (payment: any) => { try { const verified = await post('/api/payments/verify', { order_id: result.id, razorpay_payment_id: payment.razorpay_payment_id, razorpay_signature: payment.razorpay_signature }); if (verified.status !== 'captured') setError('Payment is pending provider confirmation.'); await query.invalidateQueries({ queryKey: ['policy', policyId] }); } catch (e) { setError((e as Error).message); } } });
        checkout.on('payment.failed', () => setError('The test provider reported a failed payment. No receipt has been recorded.')); checkout.open();
      }
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function simulate(result: string) { setBusy(true); setError(''); try { await post(`/api/payment-orders/${order.id}/simulate`, { result }); setOrder(null); await query.invalidateQueries({ queryKey: ['policy', policyId] }); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (policy.isLoading) return <Loading/>; if (policy.error) return <ErrorView error={policy.error}/>; const data = policy.data; const p = data.plan; const verified = data.status === 'demo_active';
  return <><div className="page-heading compact"><div><span className="eyebrow">YOUR POLICY</span><h1>{p.name}</h1><p>All the important details. Ready when you need them.</p></div><span className="badge neutral">{verified ? 'Demo policy · no real cover' : 'Unverified import'}</span></div>
    <div className="tabs wide-tabs" role="tablist" aria-label="Policy sections">{['Overview', 'Payments', 'Nearby care', 'Ask Helm'].map(t => <button role="tab" aria-selected={t === tab} onClick={() => setTab(t)} key={t}>{t}</button>)}</div>
    {!verified && <div className="notice">Policy terms have not been verified. Premiums, network membership and benefit balances are unknown.</div>}
    {tab === 'Overview' && <><div className="metric-grid"><div><span>Coverage start</span><strong>{data.start_date}</strong><small>Saved policy date</small></div><div><span>Annual premium</span><strong>{p.annual_premium ? aed(p.annual_premium * 100) : 'Unknown'}</strong><small>{verified ? 'Fictional catalogue amount' : 'Evidence needed'}</small></div><div><span>Network</span><strong>{p.network || 'Unknown'}</strong><small>{verified ? 'Frozen at selection' : 'Not inferred'}</small></div></div>
      {verified && <section className="surface"><h2>Know what your cover includes.</h2><dl className="coverage-grid"><div><dt>Annual cover limit</dt><dd>{aed(p.annual_limit * 100)}</dd><small>Remaining balance requires claims evidence</small></div><div><dt>Deductible</dt><dd>{aed(p.deductible * 100)}</dd><small>Applied before the member copay</small></div><div><dt>Member copay</dt><dd>{p.outpatient_copay_pct}%</dd><small>Applies after the deductible</small></div><div><dt>Maternity</dt><dd>{p.maternity.covered ? `${p.maternity.waiting_period_months}-month wait` : 'Excluded'}</dd><small>{p.maternity.covered ? `${aed(p.maternity.limit * 100)} plan-payment cap` : 'No maternity benefit'}</small></div><div><dt>Existing conditions</dt><dd>{p.chronic_preexisting.covered ? `${p.chronic_preexisting.waiting_period_months}-month wait` : 'Excluded'}</dd></div><div><dt>Dental / optical</dt><dd>{p.dental_optical}</dd></div></dl><ReadAloud text={`${p.name}. Deductible ${p.deductible} dirhams. Copay ${p.outpatient_copay_pct} percent. ${p.maternity.covered ? `Maternity cover has a ${p.maternity.waiting_period_months} month wait.` : 'Maternity is excluded.'}`}/></section>}
      <section className="surface notices"><h2>Policy updates</h2><p className="muted">{notices.data?.message || 'Checking sourced notices…'}</p></section></>}
    {tab === 'Payments' && <><div className="metric-grid"><div><span>Total scheduled</span><strong>{aed(data.total_fils)}</strong><small>Simulated schedule</small></div><div><span>Receipts recorded</span><strong>{aed(data.paid_fils)}</strong><small>Verified sandbox or local receipts</small></div><div><span>Remaining</span><strong>{aed(data.total_fils - data.paid_fils)}</strong><small>No automatic charges</small></div></div><section className="surface"><h2>Your payment schedule</h2><p className="muted">This demonstration uses {config.payment_provider === 'simulator' ? 'a local simulator' : 'Razorpay test mode'}. No real money or real policy instalment is involved.</p>{data.instalments.length ? data.instalments.map((item: any) => <div className="list-row" key={item.id}><span className="list-icon"><Wallet size={20}/></span><div><strong>Instalment {item.position} · {aed(item.amount)}</strong><small>Due {item.due_date} · {item.status === 'paid' ? 'Receipt recorded' : 'Not paid'}</small></div>{item.status === 'paid' ? <span className="badge success">Paid in sandbox</span> : <button className="secondary" disabled={busy} onClick={() => pay(item.id)}>Pay test amount</button>}</div>) : <p>No verified schedule is available for this imported policy.</p>}
      {!!data.receipts.length && <><h3>Receipts</h3>{data.receipts.map((r: any) => <p key={r.id}>{aed(r.amount)} · {r.provider === 'simulator' ? 'Simulated locally' : 'Razorpay test'} · {r.id.slice(0, 8)}</p>)}</>}</section></>}
    {tab === 'Nearby care' && (verified ? <Providers planId={p.id}/> : <p>Verify policy terms before matching providers.</p>)}
    {tab === 'Ask Helm' && (profile.data && cases.data?.[0] ? <div className="policy-conversation"><Conversation caseId={cases.data[0].id} profile={profile.data} voice={config.voice_available} policyId={policyId}/></div> : <p>Start an insurance profile from your overview to open a conversation.</p>)}
    {order && <section className="surface simulator" role="region" aria-label="Local payment simulator"><span className="eyebrow">SIMULATED LOCALLY</span><h2>Test payment · {aed(order.amount)}</h2><p>No card details. No money moves. Choose an outcome to exercise the payment flow.</p><div className="actions"><button disabled={busy} onClick={() => simulate('captured')}>Simulate successful payment</button><button className="secondary" disabled={busy} onClick={() => simulate('failed')}>Simulate failure</button><button className="quiet" disabled={busy} onClick={() => simulate('cancelled')}>Cancel</button></div></section>}
    {error && <ErrorView error={new Error(error)}/>}</>;
}
