import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { User, Briefcase, Landmark, Building2, ArrowRight } from 'lucide-react';
import { PageShell, Section, SurfaceCard } from '../components';
import { api, aed } from '../../api';
import './HomePage.css';
function getPlanPositioning(index: number) { const positionings = ["Essential baseline coverage for peace of mind.", "The middle ground, balancing comprehensive care and value.", "Premium coverage with extensive network and benefits."]; return positionings[index] || "Clear, reliable health cover."; }
export function HomePage() { const { data: catalogue, error } = useQuery({ queryKey: ['marketplace-plans'], queryFn: () => api('/api/public/marketplace-plans') }); const { data: providers } = useQuery({ queryKey: ['marketplace-partners'], queryFn: () => api('/api/public/marketplace-partners') }); return <PageShell>
  <Section id="hero"><div className="hp-hero"><h1>Individual health cover for UAE residents.</h1><p>Whether you’re self-sponsored, freelance, on a Golden Visa, or transitioning off an employer plan, Helm AI helps you find the right cover with clarity and confidence.</p><div className="hp-hero-actions"><Link to="/login" className="m-button-primary">Find my cover <ArrowRight size={18} /></Link><Link to="/how-it-works" className="m-text-link">See how it works</Link></div><span className="hp-hero-disclaimer">Demo product - plans and pricing shown are fictional, for illustration only.</span></div></Section>
  <Section id="who-is-it-for" tinted><div className="hp-who-grid"><div className="hp-who-item"><User size={32} /><strong>Self-sponsored residents</strong><span className="hp-hero-disclaimer">Arranging your own visa and cover.</span></div><div className="hp-who-item"><Briefcase size={32} /><strong>Freelancers</strong><span className="hp-hero-disclaimer">Independent professionals needing compliance.</span></div><div className="hp-who-item"><Landmark size={32} /><strong>Golden Visa holders & Investors</strong><span className="hp-hero-disclaimer">Long-term residents exploring premium options.</span></div><div className="hp-who-item"><Building2 size={32} /><strong>Leaving employer cover</strong><span className="hp-hero-disclaimer">Transitioning to individual health plans.</span></div></div></Section>
  <Section id="how-it-works-preview"><div className="hp-section-header"><h2>How it works</h2><p>A simple, conversational approach to finding insurance.</p></div><div className="hp-steps-grid"><SurfaceCard className="hp-step-card"><span className="hp-step-number">Step 1</span><h3>Tell us about you</h3><p>Share your needs and preferences through a simple conversation.</p></SurfaceCard><SurfaceCard className="hp-step-card"><span className="hp-step-number">Step 2</span><h3>We compare 3 plan structures</h3><p>See exactly how our plans measure up to your requirements.</p></SurfaceCard><SurfaceCard className="hp-step-card"><span className="hp-step-number">Step 3</span><h3>Get a clear recommendation</h3><p>Review the tradeoffs and choose the plan that fits best.</p></SurfaceCard><SurfaceCard className="hp-step-card"><span className="hp-step-number">Step 4</span><h3>A reviewer signs off</h3><p>Nothing is final until a human reviewer confirms the details.</p></SurfaceCard></div></Section>
  <Section id="plans-preview" tinted><div className="hp-section-header"><h2>Popular Schemes</h2><p>Fictional Helm marketplace plans for different health-care needs.</p></div>{error ? <div className="hp-teaser"><p>Plans are temporarily unavailable.</p></div> : <div className="hp-plans-grid">{catalogue?.plans?.slice(0, 3).map((plan: any, idx: number) => <SurfaceCard key={plan.id} className="hp-plan-card"><h3>{plan.name}</h3><p>{plan.provider_name} · {getPlanPositioning(idx)}</p><div className="hp-plan-price">{aed(plan.annual_premium * 100)} <span style={{ fontSize: '1rem', color: 'var(--color-ink-500)', fontWeight: 400 }}>/ year</span></div><div className="hp-plan-actions"><Link to={`/plans/${plan.id}`} className="m-text-link">View scheme <ArrowRight size={16} /></Link></div></SurfaceCard>)}</div>}<div className="hp-section-link"><Link to="/plans" className="m-button-secondary">Explore all 50 schemes</Link></div></Section>
  <Section id="partners-preview"><div className="hp-section-header"><h2>Our Partners</h2><p>10 fictional Helm marketplace partners, each with five demo schemes.</p></div><div className="hp-partners-grid">{providers?.items?.slice(0, 3).map((provider: any) => <SurfaceCard key={provider.id} className="hp-partner-card"><Building2 size={26}/><h3>{provider.name}</h3><p>{provider.scheme_count} demo schemes · {provider.emirate}</p></SurfaceCard>)}</div><div className="hp-section-link"><Link to="/partners" className="m-button-secondary">Explore all partners</Link></div></Section>
  <Section id="new-to-uae"><SurfaceCard className="hp-teaser"><h2>New to the UAE?</h2><p>Understanding local health insurance requirements can be overwhelming. We’ve put together a guide to help you navigate the system.</p><Link to="/guide" className="m-button-secondary">Read our guide</Link></SurfaceCard></Section>
  <Section id="sample-journey" tinted><div className="hp-section-header"><h2>See a sample journey</h2></div><p className="hp-journey-label">Illustrative example using demo data</p><div className="hp-journey-grid"><SurfaceCard className="hp-journey-card"><h4>1. The Profile</h4><p>Ameya, 31, moved to Dubai on an investor visa and needs comprehensive coverage.</p></SurfaceCard><SurfaceCard className="hp-journey-card"><h4>2. The Comparison</h4><p>She compares two premium plans side-by-side, prioritizing specialist access.</p></SurfaceCard><SurfaceCard className="hp-journey-card"><h4>3. The Decision</h4><p>She selects the plan that covers her preferred clinics, reviewed by a broker.</p></SurfaceCard></div></Section>
  <Section id="faq-preview"><div className="hp-section-header"><h2>Common Questions</h2></div><div className="hp-faq-list"><div className="hp-faq-item"><h3>Is this real insurance?</h3><p>No, this is a synthetic demonstration. Quotes, carriers, providers, applications and local payment schedules are fictional. No real insurance cover is issued.</p></div><div className="hp-faq-item"><h3>Does a test payment mean I am covered?</h3><p>No. A local simulation or test-provider receipt cannot activate real insurance.</p></div><div className="hp-faq-item"><h3>Can I change my answers later?</h3><p>Yes. Saved corrections update your profile and make affected old quotes stale. The terms saved with an existing policy remain unchanged.</p></div><div className="hp-faq-actions"><Link to="/faq" className="m-button-secondary">See all FAQs</Link></div></div></Section>
  <Section id="final-cta" tinted><div className="hp-final-cta"><h2>Ready to explore your options?</h2><Link to="/login" className="m-button-primary">Find my cover <ArrowRight size={18} /></Link></div></Section>
</PageShell>; }
