import { PageShell, Section, SurfaceCard } from '../components';
import './LegalPages.css';

export function TermsPage() {
  return (
    <PageShell>
      <Section id="terms-hero">
        <div className="legal-hero">
          <h1>Terms of Service</h1>
          <p>Last updated: September 2026</p>
        </div>
      </Section>

      <Section id="terms-content">
        <SurfaceCard className="legal-card">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing Helm AI, you acknowledge that this is a simulated software environment 
            designed to demonstrate insurance brokerage architectures, not a licensed insurance broker.
          </p>

          <h2>2. No Professional Advice</h2>
          <p>
            The recommendations, policy terms, and pricing generated by the Helm AI engine are 
            strictly fictional. They do not constitute legal, medical, or financial advice. You 
            cannot rely on this platform to meet real-world UAE visa or residency requirements.
          </p>

          <h2>3. Intellectual Property</h2>
          <p>
            The UI, workflows, deterministic engines, and source code architecture demonstrated here 
            remain the property of their respective creators. The fictional insurer names (e.g., Harbour, Crescent) 
            are illustrative placeholders.
          </p>

          <h2>4. Limitation of Liability</h2>
          <p>
            The creators of this demonstration accept no liability for any reliance placed upon the 
            fictional plans, synthetic pricing, or AI-generated recommendations presented within the app.
          </p>
        </SurfaceCard>
      </Section>
    </PageShell>
  );
}
